# Generated by Django 6.0.7 on 2026-07-11 12:17

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Salon',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(max_length=140, unique=True)),
                ('city', models.CharField(help_text='e.g. Accra, Kumasi, Takoradi', max_length=80)),
                ('region', models.CharField(choices=[('greater_accra', 'Greater Accra'), ('ashanti', 'Ashanti'), ('western', 'Western'), ('eastern', 'Eastern'), ('central', 'Central'), ('volta', 'Volta'), ('northern', 'Northern'), ('bono', 'Bono')], default='greater_accra', max_length=30)),
                ('address', models.CharField(max_length=255)),
                ('phone', models.CharField(blank=True, max_length=13)),
                ('opens_at', models.TimeField(default='09:00')),
                ('closes_at', models.TimeField(default='19:00')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='salons/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
