# Generated by Django 6.1.1 on 2026-09-11 21:06

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('wa_phone', models.CharField(db_index=True, help_text='WhatsApp phone number, normalized to international format e.g. +233241234567', max_length=20, unique=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('idle', 'Idle'), ('completed', 'Completed'), ('expired', 'Expired')], default='active', max_length=10)),
                ('messages', models.JSONField(blank=True, default=list, help_text='Conversation history: list of {role, content, timestamp}, oldest first')),
                ('context', models.JSONField(blank=True, default=dict, help_text="Agent's working memory for the in-progress task, e.g. draft booking fields")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_message_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('customer', models.ForeignKey(blank=True, help_text='Linked customer account, if this phone number matches a registered user', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='whatsapp_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-last_message_at'],
            },
        ),
    ]
